export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";
export const SET_ITEM = "SET_ITEM";
export const FETCH_INITIAL_STATE = "FETCH_INITIAL_STATE";
